# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'ed7d4ce5-655e-4eb0-819b-8774720c7d08'

  # Function app name
  functionAppName: 'FiDelApp'

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

# # # - stage: Test
# # #   displayName: Test stage
# # #   dependsOn: Build
# # #   condition: succeeded()

# # #   jobs:
# # #   - job: Test
# # #     displayName: Test
# # #     pool:
# # #       vmImage: $(vmImageName)
# # #     steps:
# # #     - task: UseDotNet@2
# # #       inputs:
# # #         packageType: 'sdk'
# # #         version: '6.x'
# # #       displayName: 'Use .NET SDK 6.x'

# # #     - task: PowerShell@2
# # #       inputs:
# # #         targetType: 'inline'
# # #         script: |
# # #             choco install azure-functions-core-tools
# # #             func --version
# # #             func host start &
# # #       displayName: 'Run Azure Function Locally'

# # #     - task: PowerShell@2
# # #       displayName: 'Run cURL Test'
# # #       inputs:
# # #         targetType: 'inline'
# # #         script: |
# # #           $url = "http://localhost:7071/api/FiDelApp"
# # #           $requestBody = @{
# # #               id = "0001"
# # #               categoryId = "3E4CEACD-D007-46EB-82D7-31F6141752B2"
# # #               categoryName = "Components, Road Frames"
# # #               sku = "FR-R38R-48"
# # #               name = "LL Road Frame - Red, 48"
# # #               description = "The product called 'LL Road Frame - Red, 48'"
# # #               price = 337.22
# # #               tags = @(
# # #                   @{
# # #                       id = "033D3826-2851-4B97-9464-59D3675175D4"
# # #                       name = "Tag-108"
# # #                   },
# # #                   @{
# # #                       id = "A2176C7A-4E0D-4283-AFAA-319A77E9C122"
# # #                       name = "Tag-19"
# # #                   }
# # #               )
# # #           }
# # #           $headers = @{
# # #             "Content-Type" = "application/json"
# # #           }

# # #           $requestBodyJson = $requestBody | ConvertTo-Json
# # #           $response = Invoke-RestMethod -Uri $url -Method Post -Body $requestBodyJson -Headers $headers

# # #           Write-Host "Response Body: $($response | ConvertTo-Json)"

# # #     # Add additional tasks for your specific testing requirements
# # #     # You can include assertions or validations based on the response received from the Azure Function

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

- stage: JMeterTest
  displayName: JMeter Test stage
  dependsOn: Deploy
  condition: succeeded()

  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: PowerShell@2
      displayName: 'Install Apache JMeter'
      inputs:
        targetType: 'inline'
        script: |
          $jmeterZipUrl = 'https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.zip'
          $jmeterZipPath = '$(System.DefaultWorkingDirectory)/jmeter.zip'
          $jmeterExtractPath = '$(System.DefaultWorkingDirectory)/jmeter'

          Invoke-WebRequest -Uri $jmeterZipUrl -OutFile $jmeterZipPath
          Expand-Archive -Path $jmeterZipPath -DestinationPath $jmeterExtractPath -Force
    
    - script: |
        $(System.DefaultWorkingDirectory)/jmeter/apache-jmeter-5.5/bin/jmeter -n -t $(System.DefaultWorkingDirectory)/*.jmx -l $(System.DefaultWorkingDirectory)/test_summary.jtl
      displayName: 'Run JMeter Test'
      
      # -Jthreads=100
    - script: |
        cat $(System.DefaultWorkingDirectory)/test_summary.jtl
      displayName: 'Explore results'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/test_summary.jtl'
        artifact: 'JTLResults'

- stage: ChatGPT
  displayName: ChatGPT stage
  dependsOn: JMeterTest
  condition: succeeded()

  jobs:
  - job: Chat
    displayName: ChatGPT
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download JTL Results Artifact'
      inputs:
        artifactName: 'JTLResults'
        targetPath: '$(System.DefaultWorkingDirectory)'
      
    - task: PowerShell@2
      displayName: 'Prepare JTL Results and Function Code'
      inputs:
        targetType: 'inline'
        script: |
          echo "Function Code:"
          cat $(System.DefaultWorkingDirectory)/*.cs
          cat $(System.DefaultWorkingDirectory)/*.cs > $(System.DefaultWorkingDirectory)/function_code.txt
          echo "JTL Results:"
          cat $(System.DefaultWorkingDirectory)/test_summary.jtl
          cat $(System.DefaultWorkingDirectory)/test_summary.jtl > $(System.DefaultWorkingDirectory)/jtl_results.txt

    - task: PowerShell@2
      displayName: 'List contents of DefaultWorkingDirectory'
      inputs:
        targetType: 'inline'
        script: |
          $directory = "$(System.DefaultWorkingDirectory)"
          Get-ChildItem -Path $directory

    - task: PowerShell@2
      displayName: 'Call ChatGPT API'
      inputs:
        targetType: 'inline'
        script: |
          $jtlResultsFile = "$(System.DefaultWorkingDirectory)/jtl_results.txt"
          $functionCodeFile = "$(System.DefaultWorkingDirectory)/function_code.txt"
          $apiKey = "4c7be06a162641039767063e4830a371"
          $apiUrl = "https://apchatgpt.openai.azure.com/openai/deployments/gpt-chat/chat/completions?api-version=2023-03-15-preview"

          # Read JTL results
          $jtlResults = Get-Content -Path $jtlResultsFile

          # Read function code
          $functionCode = Get-Content -Path $functionCodeFile

          # Prepare payload for API request
           $payload = @{
              messages = @(
                @{ role = 'system'; content = 'You are a system that analyzes source code and JMeter results to assist any type of developer in enhancing and improving performance in the code.' },
                @{ role = 'user'; content = "Provide me exmaple on how could imporve the Function code, dased on Function code and JTL Results:\n----\nJTL Results:\n---\n$jtlResults\n---\nFunction Code:\n---\n$functionCode\n---\n----"}
              )
              temperature = 0.7
              max_tokens = 1000
          }
          $payloadJson = $payload | ConvertTo-Json

          # Make API request
          $headers = @{
              "Content-Type" = "application/json"
              "api-key" = $apiKey
          }
          $response = Invoke-RestMethod -Uri $apiUrl -Headers $headers -Method Post -Body $payloadJson
          # Process the API response as needed
          # For example, extract and utilize the generated text
          $generatedText = $response.choices[0].message.content

          # Display the generated text
          Write-Host $generatedText

          $generatedText | Out-File "$(System.DefaultWorkingDirectory)/generatedText.txt" -Encoding utf8

    - task: PowerShell@2
      displayName: 'Send Telegram Notification'
      inputs:
        targetType: 'inline'
        script: |
          $telegramBotToken = '6096186625:AAHcTptWfiK5CIAmSEcmjEtpfJA1oiKGR_Q'
          $chatId = '549538016'
          $generatedText = Get-Content -Path "$(System.DefaultWorkingDirectory)/generatedText.txt"
          $message = @"
          The pipeline has completed successfully.
          Generated Text:
          ---
          $generatedText
          ---
          "@

          $uri = "https://api.telegram.org/bot$telegramBotToken/sendMessage"
          $body = @{
              chat_id = $chatId
              text = $message
          } | ConvertTo-Json

          Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType 'application/json'