
stages:
- stage: JMeterTest
  displayName: JMeter Test stage
  dependsOn: Deploy
  condition: succeeded()

  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: PowerShell@2
      displayName: 'Install Apache JMeter'
      inputs:
        targetType: 'inline'
        script: |
          $jmeterZipUrl = 'https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.zip'
          $jmeterZipPath = '$(System.DefaultWorkingDirectory)/jmeter.zip'
          $jmeterExtractPath = '$(System.DefaultWorkingDirectory)/jmeter'

          Invoke-WebRequest -Uri $jmeterZipUrl -OutFile $jmeterZipPath
          Expand-Archive -Path $jmeterZipPath -DestinationPath $jmeterExtractPath -Force
    
    - script: |
        $(System.DefaultWorkingDirectory)/jmeter/apache-jmeter-5.6/bin/jmeter -n -t $(System.DefaultWorkingDirectory)/*.jmx -l $(System.DefaultWorkingDirectory)/test_summary.jtl -Jthreads=10 -Jrampup=1 -Jloops=10
      displayName: 'Run JMeter Test'

    - script: |
        cat $(System.DefaultWorkingDirectory)/test_summary.jtl
      displayName: 'Explore results'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/test_summary.jtl'
        artifact: 'JTLResults'
